CREATE GLOBAL TEMPORARY TABLE DATOS_INSERCION
(
  NOMBRE_TABLA                VARCHAR2(100 BYTE),
  NOMBRE_CAMPO                VARCHAR2(400 BYTE),
  VALOR                       VARCHAR2(4000 BYTE),
  ES_ID                       VARCHAR2(1 BYTE),
  DOMINIO                     VARCHAR2(100 BYTE),
  OBLIGATORIEDAD_APARTAMENTO  VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_BODEGA       VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_CASA         VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_CASARURAL    VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_LOCAL        VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_LOTE         VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_LOTEURBANO   VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_OFICINA      VARCHAR2(300 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


