CREATE TABLE LISTA_VALORES
(
  LV_NOMBRE        VARCHAR2(30 BYTE)            NOT NULL,
  INSTRUCCION_SQL  VARCHAR2(2000 BYTE)          NOT NULL,
  FILTER           VARCHAR2(2000 BYTE),
  ESQUEMA          VARCHAR2(32 BYTE),
  DESCRIPCION      VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


