CREATE TABLE PARAMETROS_INSERCION
(
  NOMBRE_TABLA    VARCHAR2(100 BYTE),
  NOMBRE_CAMPO    VARCHAR2(400 BYTE),
  VALOR           VARCHAR2(4000 BYTE),
  VALOR_ES_QUERY  VARCHAR2(1 BYTE),
  TIPO_DATO       VARCHAR2(400 BYTE),
  ES_FK           VARCHAR2(1 BYTE),
  ES_ID           VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


