CREATE TABLE PERFIL
(
  CODIGO_PERFIL          VARCHAR2(15 BYTE),
  NOMBRE_PERFIL          VARCHAR2(60 BYTE)      NOT NULL,
  NUMERO_ACCESOS_PERFIL  NUMBER(10)             NOT NULL,
  FECHA_VENCIMIENTO      DATE,
  FECHA_TRANSACCION      DATE                   NOT NULL,
  USUARIO_TRANSACCION    VARCHAR2(13 BYTE)      NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


