CREATE TABLE PGB_ANEXO_FOTOGRAFICO
(
  ID_ANEXO_FOTOGRAFICO  NUMBER(10)              NOT NULL,
  ID_AVALUO             NUMBER                  NOT NULL,
  ID_IMG_FACHADA        NUMBER,
  ID_DOC_ANEXOS         NUMBER,
  USUARIO_CREACION      VARCHAR2(15 BYTE)       NOT NULL,
  FECHA_CREACION        DATE                    NOT NULL,
  USUARIO_TRANSACCION   VARCHAR2(15 BYTE)       NOT NULL,
  FECHA_TRANSACCION     DATE                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


