CREATE TABLE PGB_COMPLEMENTOS_EXCEL
(
  ID_COMPLEMENTO_EXCEL     NUMBER(5)            NOT NULL,
  ID_ARCHIVO               NUMBER(5)            NOT NULL,
  USUARIO_CREACION         VARCHAR2(15 BYTE),
  FECHA_CREACION           DATE,
  USUARIO_TRANSACCION      VARCHAR2(15 BYTE),
  FECHA_TRANSACCION        DATE,
  ORDEN_DESCARGA           VARCHAR2(255 BYTE),
  DESCRIPCION_COMPLEMENTO  VARCHAR2(255 BYTE),
  TEXTO_LIBRE              VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


