CREATE TABLE PGB_FORMATO_AVALUO
(
  ID_FORMATO_AVALUO    NUMBER(5)                NOT NULL,
  ID_ARCHIVO           NUMBER(5)                NOT NULL,
  DESCRICPION          VARCHAR2(250 BYTE)       NOT NULL,
  FECHA_ACTUALIZACION  DATE                     NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


