CREATE TABLE PGB_CALENDARIOS
(
  ID_CALENDARIO        NUMBER                   NOT NULL,
  ANIO                 NUMBER                   NOT NULL,
  FECHA_NO_HABIL       DATE                     NOT NULL,
  USUARIO_CREACION     VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_CREACION       DATE                     NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


