CREATE TABLE PGB_HORAS_CORTE_ARCHIVO
(
  ID_HORAS_CORTE_ARCHIVO  NUMBER                NOT NULL,
  HORA_CORTE              NUMBER(2)             NOT NULL,
  MINUTOS_CORTE           NUMBER(2)             NOT NULL,
  ESTADO                  VARCHAR2(1 BYTE)      DEFAULT 'A',
  USUARIO_CREACION        VARCHAR2(15 BYTE)     NOT NULL,
  FECHA_CREACION          DATE                  NOT NULL,
  USUARIO_TRANSACCION     VARCHAR2(15 BYTE)     NOT NULL,
  FECHA_TRANSACCION       DATE                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


