CREATE TABLE PGB_PERITOS_EMPRESAS
(
  ID_PERITO_EMPRESA    NUMBER(3)                NOT NULL,
  ID_EMPRESA_AVALUO    NUMBER(3)                NOT NULL,
  TIPO_DOCUMENTO       VARCHAR2(3 BYTE)         NOT NULL,
  NUMERO_DOCUMENTO     NUMBER(16)               NOT NULL,
  USUARIO_CREACION     VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_CREACION       DATE                     NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL,
  ESTADO_ASOCIACION    VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


