CREATE TABLE PGB_ARCHIVO_PLANO
(
  CONSECUTIVO_PLANO           NUMBER(3),
  TABLA_BD                    VARCHAR2(100 BYTE),
  COLUMNA_BD                  VARCHAR2(200 BYTE),
  TIPO_DATO                   VARCHAR2(100 BYTE),
  FORMATO                     VARCHAR2(500 BYTE),
  DOMINIO                     VARCHAR2(100 BYTE),
  OBLIGATORIEDAD_APARTAMENTO  VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_BODEGA       VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_CASA         VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_CASARURAL    VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_LOCAL        VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_LOTE         VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_LOTEURBANO   VARCHAR2(300 BYTE),
  OBLIGATORIEDAD_OFICINA      VARCHAR2(300 BYTE),
  ES_ID                       VARCHAR2(1 BYTE),
  FUNCION_CONVERSION          VARCHAR2(300 BYTE),
  ES_ASOBANCARIA              VARCHAR2(1 BYTE),
  DESCRIPCION_CAMPO           VARCHAR2(300 BYTE),
  LONGITUD_VISUAL_CAMPO       NUMBER,
  es_cargue_masivo            VARCHAR2(1),
  orden_malla                 NUMBER,
  estado_campo                VARCHAR2(1),
  PESTANA_FORMULARIO		  VARCHAR2(1000)			
  
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


