CREATE TABLE PGB_MAESTRO_CARGUES
(
  ID_MAESTRO_CARGUE    NUMBER(10)               NOT NULL,
  SECUENCIA_ARCHIVO    NUMBER(10)               NOT NULL,
  ESTADO               VARCHAR2(1 BYTE)         NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL,
  NUM_REGISTROS        NUMBER(6)                NOT NULL,
  TIENE_ANEXOS         VARCHAR2(1 BYTE),
  NOMBRE_ARCHIVO       VARCHAR2(250 BYTE)       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


