CREATE TABLE PGB_ALARMAS
(
  ID_ALARMA            NUMBER(3)                NOT NULL,
  DESC_ALERTA          VARCHAR2(250 BYTE)       NOT NULL,
  NUM_DIAS             NUMBER(3)                NOT NULL,
  USUARIO_CREACION     VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_CREACION       DATE                     NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


