CREATE TABLE PGB_COMP_OFERTA_DEMANDA
(
  ID_COMPOFERTADEMANDA  NUMBER(10),
  ID_AVALUO             NUMBER                  NOT NULL,
  T_ACTEDIFICADORA      VARCHAR2(500 BYTE),
  T_COMPORTAOD          VARCHAR2(500 BYTE),
  N_TIPOCOMERCIALIZA    NUMBER(3),
  USUARIO_CREACION      VARCHAR2(15 BYTE)       NOT NULL,
  FECHA_CREACION        DATE                    NOT NULL,
  USUARIO_TRANSACCION   VARCHAR2(15 BYTE)       NOT NULL,
  FECHA_TRANSACCION     DATE                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


