CREATE TABLE PGB_BLOQ_LOGS_GENERA_ARCHIVOS 
(
  ID_GENERACION_PLANO NUMBER, 
  FECHA_DESDE DATE, 
  FECHA_HASTA DATE, 
  FECHA_INICIO_CREACION DATE, 
  FECHA_FIN_CREACION DATE, 
  FECHA_TRANSACCION DATE, 
  USUARIO_CREACION VARCHAR2(15), 
  USUARIO_TRANSACCION VARCHAR2(15), 
  ESTADO_REGISTRO VARCHAR2(1) DEFAULT 'A'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;