CREATE TABLE PGB_HIST_LOGS_GENERA_ARCH 
   (
  ID_HIST_LOGS_GENERA_ARCH NUMBER, 
  ID_LOG_ARCHIVOS NUMBER, 
  NOMBRE_ARCHIVO VARCHAR2(200), 
  FECHA_DESDE DATE, 
  FECHA_HASTA DATE, 
  ESTADO VARCHAR2(1), 
  ENVIADO VARCHAR2(1), 
  LINK_DESCARGA VARCHAR2(500), 
  CODIGO_ERROR NUMBER, 
  DESC_ERROR VARCHAR2(4000), 
  USUARIO_CREACION VARCHAR2(15), 
  FECHA_INICIO_CREACION DATE, 
  FECHA_FIN_CREACION DATE, 
  NOMBRE_PLANO VARCHAR2(200),
  USUARIO_TRANSACCION VARCHAR2(15),
  FECHA_TRANSACCION DATE 
   )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


