CREATE TABLE PGB_ERRORES_CARGUES
(
  ID_ERROR_CARGUE      NUMBER(10)               NOT NULL,
  ID_MAESTRO_CARGUE    NUMBER(10)               NOT NULL,
  SECUENCIA_ARCHIVO    NUMBER(10)               NOT NULL,
  DESC_ERROR_CARGUE    VARCHAR2(250 BYTE)       NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(15 BYTE)        NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


