CREATE TABLE RECARGA_LISTA_VALORES
(
  LV_NOMBRE  VARCHAR2(30 BYTE)                  NOT NULL,
  TAREA      VARCHAR2(15 BYTE)                  NOT NULL,
  BLOQUE     NUMBER(2)                          NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


