CREATE TABLE SALARIO_MINIMO
(
  ANHO              NUMBER(4)                   NOT NULL,
  USUARIO_CREACION  VARCHAR2(15 BYTE)           NOT NULL,
  FECHA_CREACION    DATE                        NOT NULL,
  VALOR_SALARIO     NUMBER(9)                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


