CREATE TABLE TAREA
(
  CODIGO_TAREA         VARCHAR2(20 BYTE),
  CODIGO_MODULO        VARCHAR2(15 BYTE)        NOT NULL,
  DESCRIPCION_TAREA    VARCHAR2(120 BYTE)       NOT NULL,
  TIPO_TAREA           VARCHAR2(2 BYTE)         NOT NULL,
  FECHA_TRANSACCION    DATE                     NOT NULL,
  USUARIO_TRANSACCION  VARCHAR2(13 BYTE)        NOT NULL,
  MARCA_ACTIVO         VARCHAR2(1 BYTE),
  SUB_MODULO           VARCHAR2(50 BYTE),
  ORDEN                NUMBER(3),
  TIPO_CONTENIDO       NUMBER(2),
  CONTENIDO            VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


