CREATE TABLE TAREA_LISTA_VALORES
(
  TAREA       VARCHAR2(20 BYTE)                 NOT NULL,
  ID_BLOQUE   NUMBER                            NOT NULL,
  LV_NOMBRE   VARCHAR2(200 BYTE)                NOT NULL,
  CAMPO       VARCHAR2(32 BYTE)                 NOT NULL,
  RETORNO     VARCHAR2(255 BYTE),
  ASIGNACION  VARCHAR2(200 BYTE),
  TIPO        VARCHAR2(20 BYTE),
  ESTADO      VARCHAR2(1 BYTE),
  FILTER      VARCHAR2(2000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


