DROP MATERIALIZED VIEW V_AVALUOS_ARGIS_FACHADA;
CREATE MATERIALIZED VIEW V_AVALUOS_ARGIS_FACHADA
REFRESH FORCE ON DEMAND
AS
SELECT
  PGB_AVA.ID_AVALUO,
  PGB_ARC.CONTENIDO FACHADA
FROM PGB_AVALUOS PGB_AVA,
     PGB_ANEXO_FOTOGRAFICO PGB_FOTO,
     ARCHIVOS PGB_ARC
WHERE PGB_FOTO.ID_AVALUO = PGB_AVA.ID_AVALUO
  AND PGB_FOTO.ID_IMG_FACHADA = PGB_ARC.ID_ARCHIVO
  AND PGB_AVA.A_ESTADOAVALUO = 3;

grant all on avaluos.v_avaluos_argis_fachada to public;