CREATE MATERIALIZED VIEW V_AVALUOS_SF
REFRESH FORCE ON DEMAND
AS
SELECT PGB_AVA.ID_AVALUO,
  --09 Abr 2014: Circular 11
  PGB_IC.A_RCONS_SF A_RCONS_SF_COD
  ,PGB_IC.A_DANOPREVIO_SF A_DANOPREVIO_SF_COD
  ,PGB_IC.C_ESTREFORZADA_SF C_ESTREFORZADA_SF_COD
  ,PGB_IC.A_DANOREPARADO_SF A_DANOREPARADO_SF_COD
  ,PGB_IC.SIMETRIA_ALT_SF SIMETRIA_ALT_SF_COD
  ,PGB_IC.SIMETRIA_PLANT_SF SIMETRIA_PLANT_SF_COD
  ,PGB_IC.C_MATERIAL_SF C_MATERIAL_SF_COD
  ,PGB_IC.C_DETALLEMATERIAL C_DETALLEMATERIAL_COD
  ,PGB_IF.C_USOINMUEBLE_SF C_USOINMUEBLE_SF_COD
FROM PGB_AVALUOS PGB_AVA,
     PGB_CONDSALUBRIDAD PGB_CS,
     PGB_INFBARRIO PGB_IB,
     PGB_INFCONSTRUCCION PGB_IC,
     PGB_INFINMUEBLE PGB_IF,
     PGB_LIQAVALUO PGB_LIQ,
     (select min(consecutivo) consecutivo,id_avaluo from pgb_liqavaluo group by id_avaluo) Liquidaciones,
     PGB_LIQAVALUO_TOTAL PGB_LIQ_T,
     PGB_OBSERVACIONES PGB_OBS
WHERE PGB_AVA.ID_AVALUO = PGB_CS.ID_AVALUO
  AND PGB_CS.ID_AVALUO = PGB_IB.ID_AVALUO
  AND PGB_IB.ID_AVALUO = PGB_IC.ID_AVALUO
  AND PGB_IC.ID_AVALUO = PGB_IF.ID_AVALUO
  AND PGB_IF.ID_AVALUO = PGB_LIQ.ID_AVALUO
  AND PGB_LIQ.ID_AVALUO = PGB_LIQ_T.ID_AVALUO
  AND PGB_LIQ_T.ID_AVALUO = PGB_OBS.ID_AVALUO
  AND PGB_LIQ.CONSECUTIVO = Liquidaciones.consecutivo
  AND PGB_LIQ.ID_AVALUO = Liquidaciones.ID_AVALUO
  AND PGB_AVA.A_ESTADOAVALUO = 3

UNION

SELECT PGB_AVA.ID_AVALUO,
  --09 Abr 2014: Circular 11
  PGB_IC.A_RCONS_SF A_RCONS_SF_COD
  ,PGB_IC.A_DANOPREVIO_SF A_DANOPREVIO_SF_COD
  ,PGB_IC.C_ESTREFORZADA_SF C_ESTREFORZADA_SF_COD
  ,PGB_IC.A_DANOREPARADO_SF A_DANOREPARADO_SF_COD
  ,PGB_IC.SIMETRIA_ALT_SF SIMETRIA_ALT_SF_COD
  ,PGB_IC.SIMETRIA_PLANT_SF SIMETRIA_PLANT_SF_COD
  ,PGB_IC.C_MATERIAL_SF C_MATERIAL_SF_COD
  ,PGB_IC.C_DETALLEMATERIAL C_DETALLEMATERIAL_COD
  ,PGB_IF.C_USOINMUEBLE_SF C_USOINMUEBLE_SF_COD
FROM PGB_AVALUOS PGB_AVA,
     PGB_CONDSALUBRIDAD PGB_CS,
     PGB_INFBARRIO PGB_IB,
     PGB_INFCONSTRUCCION PGB_IC,
     PGB_INFINMUEBLE PGB_IF,
     PGB_OBSERVACIONES PGB_OBS
WHERE PGB_AVA.ID_AVALUO = PGB_CS.ID_AVALUO(+)
  AND PGB_CS.ID_AVALUO = PGB_IB.ID_AVALUO(+)
  AND PGB_IB.ID_AVALUO = PGB_IC.ID_AVALUO(+)
  AND PGB_IC.ID_AVALUO = PGB_IF.ID_AVALUO(+)
  AND PGB_IF.ID_AVALUO = PGB_OBS.ID_AVALUO(+)
  AND PGB_AVA.A_ESTADOAVALUO = 3
  AND PGB_AVA.ID_AVALUO NOT IN
  (select id_avaluo from pgb_liqavaluo);
