CREATE OR REPLACE SYNONYM ARCAVAL.V_AVALUOS_ARGIS FOR AVALUOS.V_AVALUOS_ARGIS;
CREATE OR REPLACE SYNONYM AVALUOS_ARCGIS.V_AVALUOS_ARGIS FOR AVALUOS.V_AVALUOS_ARGIS;
CREATE OR REPLACE PUBLIC SYNONYM V_AVALUOS_ARGIS FOR AVALUOS.V_AVALUOS_ARGIS;
CREATE OR REPLACE SYNONYM DS_AVALUOS.V_AVALUOS_ARGIS FOR AVALUOS.V_AVALUOS_ARGIS;   
/