
SET SQLBLANKLINES ON;
SET DEFINE OFF;

--
-- Updating data of table AVALUOS.cg_ref_codes
--



INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '1', NULL, NULL, 'Desconocido'||CHR(10)
, '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '2', NULL, NULL, 'Antes de 1963', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '3', NULL, NULL, '1963-1977', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '4', NULL, NULL, '1978-1984', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '5', NULL, NULL, '1985-1997 ', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '6', NULL, NULL, '1998-2010', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'RANGO_CONSTRUCCION_SF', '7', NULL, NULL, '2011 en adelante', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SIMETRIA_SF', '0', NULL, NULL, 'No Disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SIMETRIA_SF', '1', NULL, NULL, 'Con Irregularidad', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SIMETRIA_SF', '2', NULL, NULL, 'Sin Irregularidad', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_DANOPREVIO_SF', '0', NULL, NULL, 'No Disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_DANOPREVIO_SF', '1', NULL, NULL, 'Con daños Previos', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_DANOPREVIO_SF', '2', NULL, NULL, 'Sin daños Previos', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_DANOREPARADO_SF', '0', NULL, NULL, 'No Disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_DANOREPARADO_SF', '1', NULL, NULL, 'Reparados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_DANOREPARADO_SF', '2', NULL, NULL, 'No Reparados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_REFORZADA_SF', '0', NULL, NULL, 'No Aplica', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_REFORZADA_SF', '1', NULL, NULL, 'Trabes Coladas en sitio', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_REFORZADA_SF', '2', NULL, NULL, 'Trabes Prefabricados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'A_REFORZADA_SF', '3', NULL, NULL, 'No tiene Trabes', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'MATEST_BUA', '1', NULL, NULL, 'Concreto Reforzado', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'MATEST_BUA', '2', NULL, NULL, 'Mampostería', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'MATEST_BUA', '3', NULL, NULL, 'Acero', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'MATEST_BUA', '4', NULL, NULL, 'Madera', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'MATEST_BUA', '5', NULL, NULL, 'Adobe   , bahareque o tapia', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'MATEST_BUA', '6', NULL, NULL, 'Mixta u Otra', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '1', '1', NULL, 'Vivienda', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '2', NULL, NULL, 'Comercial', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '3', NULL, NULL, 'Educación', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '4', NULL, NULL, 'Salud', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '5', NULL, NULL, 'Hotelero', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '6', '4', NULL, 'Oficinas', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '7', NULL, NULL, 'Industrial', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '8', NULL, NULL, 'Iglesia', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '9', NULL, NULL, 'Bodegas', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '10', NULL, NULL, 'Parqueaderos', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '11', NULL, NULL, 'Auditorios', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '12', NULL, NULL, 'Instalaciones deportivas', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '13', '6', NULL, 'Otros', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_USOINMUEBLE_SF', '14', '5', NULL, 'V. Multihabitacional', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'IRREGULARIDAD_BUA', '1', '0', NULL, 'No disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'IRREGULARIDAD_BUA', '2', '1', NULL, 'Con irregularidad', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'IRREGULARIDAD_BUA', '3', '2', NULL, 'Sin irregularidad', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'REPARADOS_BUA', '1', '0', NULL, 'No disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'REPARADOS_BUA', '2', '1', NULL, 'Reparados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'REPARADOS_BUA', '3', '2', NULL, 'No reparados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURAREFORZADA_BUA', '1', '0', NULL, 'No disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURAREFORZADA_BUA', '2', '1', NULL, 'Trabes coladas en sitio', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURAREFORZADA_BUA', '3', '2', NULL, 'Trabes prefabricadas', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURAREFORZADA_BUA', '4', '3', NULL, 'No tiene trabes', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SISTEMACOORDENADAS_BUA', '1', NULL, NULL, 'MAGNA SIRGAS', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SISTEMACOORDENADAS_BUA', '2', NULL, NULL, 'WGS82', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SISTEMACOORDENADAS_BUA', '3', NULL, NULL, 'WGS84', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'SISTEMACOORDENADAS_BUA', '4', NULL, NULL, 'Otro', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'DANOSPREVIOS_BUA', '1', '0', NULL, 'No Disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'DANOSPREVIOS_BUA', '2', '1', NULL, 'Con daños Previos', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'DANOSPREVIOS_BUA', '3', '2', NULL, 'Sin daños Previos', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '1', '1-12', NULL, 'Concreto Reforzado - Pórticos', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '2', '7-99', NULL, 'Concreto Reforzado- Muros', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '3', '7-99', NULL, ' Concreto Reforzado - Sistema dual o combinado', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '4', '1-7', NULL, 'Concreto Reforzado - Paneles prefabricados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '5', '4-16', NULL, 'Concreto Reforzado - Reticular celulado', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '6', '1-99', NULL, 'Concreto Reforzado - Desconocido', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '7', '1-99', NULL, 'Mampostería - Mampostería confinada', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '8', '1-99', NULL, 'Mampostería - Mampostería reforzada', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '9', '1-99', NULL, 'Mampostería - Mampostería no reforzada', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '10', '1-99', NULL, 'Mampostería - Desconocido ', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '11', '1-99', NULL, 'Acero - Pórticos arriostrados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '12', '1-99', NULL, 'Acero - Pórticos no arriostrados', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '13', '1-99', NULL, 'Acero - Desconocido', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '14', '1-99', NULL, 'Madera - Pórticos y paneles en madera', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '15', '1-99', NULL, 'Madera - Desconocido', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '16', '1-99', NULL, 'Adobe - bahareque - tapia- Adobe', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '17', '1-99', NULL, 'Adobe - bahareque - tapia - Tapia', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '18', '1-99', NULL, 'Adobe - bahareque - tapia- Bahareque', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '19', '1-99', NULL, 'Adobe - Desconocido', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '20', NULL, NULL, '(No BUA)Mixtas u Otro* ', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTRUCTURA_SF_BUA', '21', NULL, NULL, '(No SF)No disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURA2_BUA', '27', '1', NULL, 'Concreto Reforzado', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURA2_BUA', '28', '2', NULL, 'Mampostería', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURA2_BUA', '29', '3', NULL, 'Acero', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURA2_BUA', '30', '4', NULL, 'Madera', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURA2_BUA', '31', '5', NULL, 'Adobe, bahareque o tapia', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'ESTRUCTURA2_BUA', '32', '6', NULL, 'Mixtas u Otra', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '80', NULL, NULL, 'Educación', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '81', NULL, NULL, 'Salud', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '82', NULL, NULL, 'Hotelero', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '83', NULL, NULL, 'Industrial', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '84', NULL, NULL, 'Iglesia', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '85', NULL, NULL, 'Parqueadero', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '86', NULL, NULL, 'Auditorio', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '87', NULL, NULL, 'Instalación Deportiva', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTREFORZADA_SF', '0', NULL, NULL, 'No disponible', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTREFORZADA_SF', '1', NULL, NULL, 'Trabes coladas en sitio', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTREFORZADA_SF', '2', NULL, NULL, 'Trabes prefabricadas', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_ESTREFORZADA_SF', '3', NULL, NULL, 'No tiene trabes', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_MATERIAL_SF', '1', NULL, NULL, 'Concreto Reforzado', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_MATERIAL_SF', '2', NULL, NULL, 'Mampostería', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_MATERIAL_SF', '3', NULL, NULL, 'Acero', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_MATERIAL_SF', '4', NULL, NULL, 'Madera', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_MATERIAL_SF', '5', NULL, NULL, 'Adobe, bahareque o tapia', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'C_MATERIAL_SF', '6', NULL, NULL, 'Mixtas u Otra', '80093644');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '4', '4', NULL, 'Oficina', 'PERITO');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '5', '5', NULL, 'V. Multihabitacional', 'PERITO');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '6', '6', NULL, 'Otro', 'PERITO');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '1', '1', NULL, 'Vivienda', 'PERITO');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '2', NULL, NULL, 'Comercio', 'PERITO');
INSERT INTO AVALUOS.CG_REF_CODES(ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY) VALUES
(SEQ_CG_REF_CODES.NEXTVAL, 'USOINMUEBLE_BUA', '3', NULL, NULL, 'Bodegas', 'PERITO');


/

COMMIT;
