--Insert TAREA_PROCESO
INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, 
                           TRANSACCION_ALTERNA, JOIN, REFERENCES, TAB_TITLE, VALIDATE_FORM, 
                           FILE_OUTPUT, INITIAL_PARAMS, TITLE_DATA, DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0006', 'baseweb.ServPrograma', 'SELECT LPAD('' -> '', LEVEL*5)||C.MENU AS MENU,
       C.CODIGO_TAREA,
       C.DESCRIPCION_TAREA,
       C.PADRE,
       C.NOMBRE_PADRE,
       C.FECHA_TRANSACCION, 
       C.USUARIO_TRANSACCION, 
       C.ESTADO_ACTIVO
  FROM ( SELECT T.DESCRIPCION_TAREA AS MENU,
                T.CODIGO_TAREA AS CODIGO_TAREA,
                T.DESCRIPCION_TAREA AS DESCRIPCION_TAREA,
                T.CODIGO_MODULO AS PADRE,
                (SELECT DESCRIPCION_MODULO FROM MODULO_APLICACION M WHERE M.CODIGO_MODULO = T.CODIGO_MODULO) AS NOMBRE_PADRE,
                T.FECHA_TRANSACCION AS FECHA_TRANSACCION, 
                T.USUARIO_TRANSACCION AS USUARIO_TRANSACCION, 
                T.MARCA_ACTIVO AS ESTADO_ACTIVO
           FROM TAREA T
        UNION
         SELECT (SELECT DESCRIPCION_MODULO FROM MODULO_APLICACION M WHERE M.CODIGO_MODULO = T.CODIGO_MODULO) AS MENU,
                T.CODIGO_MODULO AS CODIGO_TAREA,
                (SELECT DESCRIPCION_MODULO FROM MODULO_APLICACION M WHERE M.CODIGO_MODULO = T.CODIGO_MODULO) AS DESCRIPCION_TAREA,
                NULL AS PADRE,
                NULL AS NOMBRE_PADRE,
                NULL AS FECHA_TRANSACCION, 
                NULL AS USUARIO_TRANSACCION, 
                NULL AS ESTADO_ACTIVO
           FROM TAREA T
         ) C
START WITH C.PADRE IS NULL
CONNECT BY PRIOR C.CODIGO_TAREA = C.PADRE', '', 0, '', '', '', '', 'S', 'Programa.jsp', '', '', '', 2, 0);

COMMIT;
/

