
alter table AVALUOS.REF_OLD_NEW_DOMAIN
  add constraint REF_OLD_NEW_DOMAIN_UK unique (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR);
--
-- Deleting data from table AVALUOS.REF_OLD_NEW_DOMAIN
--
DELETE FROM AVALUOS.REF_OLD_NEW_DOMAIN WHERE OLD_DOMAIN = 'A_DANOPREVIO' AND OLD_VALUE = '3' AND SF_DOMAIN = 'DANOSPREVIOS_SF' AND SF_VALUE = '1' AND SF_DESCR = 'Con daños Previos' AND BUA_DOMAIN = 'DANOSPREVIOS_BUA' AND BUA_VALUE = '2' AND BUA_DESCR = 'Con daños Previos';
DELETE FROM AVALUOS.REF_OLD_NEW_DOMAIN WHERE OLD_DOMAIN = 'A_EDISIMALT' AND OLD_VALUE = '3' AND SF_DOMAIN = 'SIMETRIA_ALT_SF'||CHR(10)
 AND SF_VALUE = '1' AND SF_DESCR = 'Con Irregularidad'||CHR(10)
 AND BUA_DOMAIN = 'IRREGULARIDAD_ALT_BUA' AND BUA_VALUE = '2' AND BUA_DESCR = 'Con Irregularidad'||CHR(10)
;
DELETE FROM AVALUOS.REF_OLD_NEW_DOMAIN WHERE OLD_DOMAIN = 'A_EDISIMPLANTA' AND OLD_VALUE = '3' AND SF_DOMAIN = 'SIMETRIA_PLANT_SF'||CHR(10)
 AND SF_VALUE = '1' AND SF_DESCR = 'Con Irregularidad'||CHR(10)
 AND BUA_DOMAIN = 'IRREGULARIDAD_PLAN_BUA' AND BUA_VALUE = '2' AND BUA_DESCR = 'Con Irregularidad'||CHR(10)
;
/

--
-- Inserting data into table AVALUOS.REF_OLD_NEW_DOMAIN
--
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('A_DANOPREVIO', '1', 'DANOSPREVIOS_SF', '0', 'No Disponible', 'DANOSPREVIOS_BUA', '1', 'No Disponible');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('A_EDISIMALT', '1', 'SIMETRIA_ALT_SF'||CHR(10)
, '0', 'No Disponible', 'IRREGULARIDAD_ALT_BUA', '1', 'No Disponible');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('A_EDISIMPLANTA', '1', 'SIMETRIA_PLANT_SF'||CHR(10)
, '0', 'No Disponible', 'IRREGULARIDAD_PLAN_BUA', '1', 'No Disponible');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('A_EDISIMPLANTA', '1', 'SIMETRIA_PLANT_SF'||CHR(10)
, '2', 'Sin irregularidad', 'IRREGULARIDAD_PLAN_BUA', '3', 'Sin irregularidad');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '0', 'A_DANOREPARADO_SF', '0', 'No disponible', 'REPARADOS_BUA', '1', 'No Disponible');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '0', 'C_ESTREFORZADA_SF', '0', 'No disponible', 'ESTRUCTURAREFORZADA_BUA', '1', 'No disponible');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '1', 'A_DANOREPARADO_SF', '1', 'Reparados', 'REPARADOS_BUA', '2', 'Reparados');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '1', 'C_ESTREFORZADA_SF', '1', 'Trabes coladas en sitio', 'ESTRUCTURAREFORZADA_BUA', '2', 'Trabes coladas en sitio');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '2', 'A_DANOREPARADO_SF', '2', 'No reparados', 'REPARADOS_BUA', '3', 'No reparados');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '2', 'C_ESTREFORZADA_SF', '2', 'Trabes prefabricadas', 'ESTRUCTURAREFORZADA_BUA', '3', 'Trabes prefabricadas');
INSERT INTO AVALUOS.REF_OLD_NEW_DOMAIN(OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR) VALUES
('NO_APLICA', '3', 'C_ESTREFORZADA_SF', '3', 'No tiene trabes', 'ESTRUCTURAREFORZADA_BUA', '4', 'No tiene trabes');
/


COMMIT;
