UPDATE AVALUOS.TAREA_PROCESO
   SET INSTRUCCION = 'SELECT TRIM(REPLACE(CODIGO_USUARIO,''"'','''')) AS COD_USUARIO,
 CODIGO_PERFIL AS "PERFIL_ASIGNADO",
 Sf_Describ_Perfil(CODIGO_PERFIL) AS "DESCRIPCION_PERFIL",
 SUBSTR(CLAVE_USUARIO,1,50) AS "CLAVE",
 CODIGO_LOCALIDAD AS "LOCALIDAD",
 SUBSTR(Sf_Localidad(CODIGO_LOCALIDAD),1,120) NOMBRE_LOCALIDAD,
 CONTADOR_ACCESOS AS "ACCESOS",
 FECHA_ACTIVACION AS "ACTIVACION",
 INDICADOR_NIVEL_SUPERVISION AS "NIVEL_SUPERVISION",
 Sf_Dominio(''NIVEL_SUPERVISION'', INDICADOR_NIVEL_SUPERVISION, ''SEGURIDAD'') TIPO_NIVEL_SUPERVISION,
 FECHA_VENCIMIENTO AS "FECHA_VENCIMIENTO",
 ESTADO_USUARIO AS "ESTADO_USUARIO",
 Sf_Dominio(''ESTADOS_USUARIO'', ESTADO_USUARIO , ''SEGURIDAD'') ESTADO_DEL_USUARIO,
 CEDULA_EMPLEADO AS "CEDULA",
 CODIGO_EMPLEADO AS "COD_EMPLEADO",
 NOMBRE_EMPLEADO AS "NOMBRE",
 TELEFONO_EMPLEADO AS "TELEFONO",
 COD_CIA COMPANIA,
 FECHA_CREACION AS "FECHA_DE_CREACION",
 USUARIO_TRANSACCION AS "USUARIO",
 FECHA_TRANSACCION AS "FECHA",
 FECHA_ULTIMO_INGRESO AS "FECHA_ULTIMO_INGRESO"
 FROM USUARIO
 WHERE COD_CIA='':COMPANIA''
 ORDER BY CODIGO_USUARIO'
 WHERE CODIGO_TAREA =  'SEGU0004'
   AND ID_BLOQUE = '0';
   
COMMIT;
/
