--INSERT V_CG_REF_CODES

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CRITICIDAD_INFORMACION', '1', '', 'MB', 'MUY BAJA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CRITICIDAD_INFORMACION', '2', '', 'BJ', 'BAJA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CRITICIDAD_INFORMACION', '3', '', 'MD', 'MEDIA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CRITICIDAD_INFORMACION', '4', '', 'AL', 'ALTA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CRITICIDAD_INFORMACION', '5', '', 'MA', 'MUY ALTA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CRITICIDAD_INFORMACION', '6', '', 'P', 'PENDIENTE', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

COMMIT;
/
