
SET SQLBLANKLINES ON;
SET DEFINE OFF;

--
-- Updating data of table AVALUOS.PGB_ARCHIVO_PLANO
--
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', OBLIGATORIEDAD_OFICINA = 'S' WHERE CONSECUTIVO_PLANO = 228 AND TABLA_BD = 'PGB_AVALUOS' AND COLUMNA_BD = 'A_UBICGPS';
/

COMMIT;
