insert into tarea_lista_valores ( TAREA, ID_BLOQUE, LV_NOMBRE, CAMPO, RETORNO, ASIGNACION, TIPO, ESTADO, FILTER)
values ('SEGU0001', 0, 'LV_CRITICIDAD_INFORMACION', 'CRITICIDAD_INF', 'CRITICIDAD_INF,DESC_CRITICIDAD', 'VALOR,DESCRIPCION', '', 'A', '');

insert into tarea_lista_valores ( TAREA, ID_BLOQUE, LV_NOMBRE, CAMPO, RETORNO, ASIGNACION, TIPO, ESTADO, FILTER)
values ('SEGU0001', 0, 'LV_CLASIFICACION_INFORMACION', 'CLASIFICACION_INF', 'CLASIFICACION_INF,DESC_CLASIFICACION', 'VALOR,DESCRIPCION', '', 'A', '');

COMMIT;
