
SET SQLBLANKLINES ON;
SET DEFINE OFF;

--
-- Updating data of table AVALUOS.REF_OLD_NEW_DOMAIN
--

prompt Loading REF_OLD_NEW_DOMAIN...
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_EDISIMPLANTA', '1', 'SIMETRIA_PLANT_SF' || chr(10) || '', '2', 'Sin irregularidad', 'IRREGULARIDAD_PLAN_BUA', '3', 'Sin irregularidad');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_EDISIMPLANTA', '2', 'SIMETRIA_PLANT_SF' || chr(10) || '', '1', 'Con Irregularidad' || chr(10) || '', 'IRREGULARIDAD_PLAN_BUA', '2', 'Con Irregularidad' || chr(10) || '');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_EDISIMPLANTA', '3', 'SIMETRIA_PLANT_SF' || chr(10) || '', '1', 'Con Irregularidad' || chr(10) || '', 'IRREGULARIDAD_PLAN_BUA', '2', 'Con Irregularidad' || chr(10) || '');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_EDISIMALT', '1', 'SIMETRIA_ALT_SF' || chr(10) || '', '2', 'Sin irregularidad', 'IRREGULARIDAD_ALT_BUA', '3', 'Sin irregularidad');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_EDISIMALT', '2', 'SIMETRIA_ALT_SF' || chr(10) || '', '1', 'Con Irregularidad' || chr(10) || '', 'IRREGULARIDAD_ALT_BUA', '2', 'Con Irregularidad' || chr(10) || '');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_EDISIMALT', '3', 'SIMETRIA_ALT_SF' || chr(10) || '', '1', 'Con Irregularidad' || chr(10) || '', 'IRREGULARIDAD_ALT_BUA', '2', 'Con Irregularidad' || chr(10) || '');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_DANOPREVIO', '1', 'DANOSPREVIOS_SF', '2', 'Sin daños Previos', 'DANOSPREVIOS_BUA', '3', 'Sin daños Previos');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_DANOPREVIO', '2', 'DANOSPREVIOS_SF', '1', 'Con daños Previos', 'DANOSPREVIOS_BUA', '2', 'Con daños Previos');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('A_DANOPREVIO', '3', 'DANOSPREVIOS_SF', '1', 'Con daños Previos', 'DANOSPREVIOS_BUA', '2', 'Con daños Previos');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '1', 'C_MATERIAL_SF', '3', 'Acero', 'ESTRUCTURA2_BUA', '29', 'Acero');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '2', 'C_MATERIAL_SF', '5', 'Adobe, bahareque o tapia', 'ESTRUCTURA2_BUA', '31', 'Adobe, bahareque o tapia');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '3', 'C_MATERIAL_SF', '1', 'Concreto Reforzado', 'ESTRUCTURA2_BUA', '27', 'Concreto Reforzado');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '4', 'C_MATERIAL_SF', '4', 'Madera', 'ESTRUCTURA2_BUA', '30', 'Madera');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '5', 'C_MATERIAL_SF', '2', 'Mampostería', 'ESTRUCTURA2_BUA', '28', 'Mampostería');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '6', 'C_MATERIAL_SF', '2', 'Mampostería', 'ESTRUCTURA2_BUA', '28', 'Mampostería');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '7', 'C_MATERIAL_SF', '3', 'Acero', 'ESTRUCTURA2_BUA', '29', 'Acero');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '8', 'C_MATERIAL_SF', '5', 'Adobe, bahareque o tapia', 'ESTRUCTURA2_BUA', '31', 'Adobe, bahareque o tapia');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('MATEST', '9', 'C_MATERIAL_SF', '6', 'Mixta u Otra', 'ESTRUCTURA2_BUA', '32', 'Mixtas u Otra');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('C_USOINMUEBLE', '1', 'C_USOINMUEBLE_SF', '1', 'Vivienda', 'C_USOINMUEBLE_BUA', '1', 'Vivienda');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('C_USOINMUEBLE', '2', 'C_USOINMUEBLE_SF', '2', 'Comercial', 'C_USOINMUEBLE_BUA', '2', 'Comercio');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('C_USOINMUEBLE', '3', 'C_USOINMUEBLE_SF', '9', 'Bodegas', 'C_USOINMUEBLE_BUA', '3', 'Bodegas');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('C_USOINMUEBLE', '4', 'C_USOINMUEBLE_SF', '6', 'Oficina', 'C_USOINMUEBLE_BUA', '4', 'Oficina');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('C_USOINMUEBLE', '5', 'C_USOINMUEBLE_SF', '14', 'V. Multihabitacional', 'C_USOINMUEBLE_BUA', '5', 'V. Multihabitacional');
insert into REF_OLD_NEW_DOMAIN (OLD_DOMAIN, OLD_VALUE, SF_DOMAIN, SF_VALUE, SF_DESCR, BUA_DOMAIN, BUA_VALUE, BUA_DESCR)
values ('C_USOINMUEBLE', '6', 'C_USOINMUEBLE_SF', '13', 'Otros', 'C_USOINMUEBLE_BUA', '6', 'Otros');

/

COMMIT;
