--Insert TAREA_PROCESO
INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, 
                           TRANSACCION_ALTERNA, JOIN, REFERENCES, TAB_TITLE,
                           VALIDATE_FORM, FILE_OUTPUT, INITIAL_PARAMS, TITLE_DATA, 
                           DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0013', 'baseweb.ServPrograma', 'SELECT HU.CODIGO_USUARIO, 
       Sf_NOMBRE_EMPLEADO(HU.CODIGO_USUARIO) NOMBRE_USUARIO, 
       HU.CODIGO_PERFIL,
       Sf_Describ_Perfil(HU.CODIGO_PERFIL) NOMBRE_PERFIL,
       HU.FECHA_CREACION,
       HU.ESTADO_USUARIO, 
       HU.FECHA_TRANSACCION ,
       HU.USUARIO_TRANSACCION 
FROM HISTORICO_USUARIO HU,
     PERFIL P
WHERE HU.CODIGO_PERFIL = P.CODIGO_PERFIL
  AND HU.FECHA_TRANSACCION = (SELECT MAX(U.FECHA_TRANSACCION) 
                              FROM HISTORICO_USUARIO U
                              WHERE U.CODIGO_PERFIL = HU.CODIGO_PERFIL)', '', 0, '', '', '', '', 'S', 'Programa.jsp', '', '', '', 2, 2);

INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, TRANSACCION_ALTERNA, JOIN, REFERENCES, TAB_TITLE, VALIDATE_FORM, FILE_OUTPUT, INITIAL_PARAMS, 
                                   TITLE_DATA, DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0013A', 'baseweb.ServPrograma', '', '', 0, '', '', '', '', '', 'sendExcel.jsp', 
        '', '', '', 16, 0);

INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, TRANSACCION_ALTERNA, JOIN, REFERENCES, TAB_TITLE, VALIDATE_FORM, FILE_OUTPUT, INITIAL_PARAMS, TITLE_DATA, DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0004A', 'baseweb.ServPrograma', 'SELECT U.CODIGO_USUARIO,
       U.NOMBRE_EMPLEADO,
       U.CODIGO_PERFIL,
       Sf_Describ_Perfil (U.CODIGO_PERFIL) NOMBRE_PERFIL,
       U.FECHA_CREACION,
       U.ESTADO_USUARIO,
       U.FECHA_TRANSACCION,
       U.USUARIO_TRANSACCION
 FROM USUARIO U
ORDER BY CODIGO_USUARIO', '', 0, '', '', '', '', 'S', 'Programa.jsp', '', '', '', 2, 2);

INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, TRANSACCION_ALTERNA, JOIN, REFERENCES, 
                                   TAB_TITLE, VALIDATE_FORM, FILE_OUTPUT, INITIAL_PARAMS, TITLE_DATA, DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0004B', 'baseweb.ServPrograma', '', '', 0, '', '', '', '', '', 'sendExcel.jsp', 
        '', '', '', 16, 0);
        
INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, 
                           TRANSACCION_ALTERNA, JOIN, REFERENCES, TAB_TITLE, VALIDATE_FORM, 
                           FILE_OUTPUT, INITIAL_PARAMS, TITLE_DATA, DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0014', 'baseweb.ServPrograma', 'SELECT TP.CODIGO_PERFIL,
       Sf_Describ_Perfil(TP.CODIGO_PERFIL) NOMBRE_PERFIL,
       T.CODIGO_TAREA,
       T.DESCRIPCION_TAREA,
       DECODE(T.MARCA_ACTIVO,''S'',''SI'',''N'',''NO'') TAREA_ACTIVA,
       DECODE(TP.PERMISO_EJECUTAR,''S'',''SI'',''N'',''NO'') PERMISO_EJECUTAR,
       DECODE(TP.PERMISO_IMPRIMIR,''S'',''SI'',''N'',''NO'') PERMISO_IMPRIMIR,
       DECODE(TP.PERMISO_ACTUALIZACION,''S'',''SI'',''N'',''NO'') PERMISO_ACTUALIZACION,
       DECODE(TP.PERMISO_ADICIONAR,''S'',''SI'',''N'',''NO'') PERMISO_ADICIONAR,
       DECODE(TP.PERMISO_BORRAR,''S'',''SI'',''N'',''NO'') PERMISO_BORRAR,
       DECODE(TP.PERMISO_CONSULTAR,''S'',''SI'',''N'',''NO'') PERMISO_CONSULTAR,
       T.FECHA_TRANSACCION,
       T.USUARIO_TRANSACCION
  FROM TAREA_PERFIL TP,
       TAREA T
 WHERE TP.CODIGO_TAREA = T.CODIGO_TAREA
 ORDER BY TP.CODIGO_PERFIL,
          T.CODIGO_TAREA', '', 0, '', '', '', '', 'S', 'Programa.jsp', '', '', '', 2, 2);


INSERT INTO AVALUOS.TAREA_PROCESO (CODIGO_TAREA, TRANSACCION, INSTRUCCION, PROCESO, ID_BLOQUE, TRANSACCION_ALTERNA, JOIN, REFERENCES, 
                                   TAB_TITLE, VALIDATE_FORM, FILE_OUTPUT, INITIAL_PARAMS, TITLE_DATA, DATASOURCE, NUM_COLUMN, INITIAL_STATED)
VALUES ('SEGU0014A', 'baseweb.ServPrograma', '', '', 0, '', '', '', '', '', 'sendExcel.jsp', 
        '', '', '', 16, 0); 
              
COMMIT;
/
