insert into lista_valores ( LV_NOMBRE, INSTRUCCION_SQL, FILTER, ESQUEMA, DESCRIPCION)
values ('LV_CRITICIDAD_INFORMACION', 'SELECT  A.LOW_VALUE VALOR, MEANING AS DESCRIPCION
FROM   V_CG_REF_CODES A
WHERE A.NAME LIKE ''CRITICIDAD_INFORMACION''
ORDER BY 2', '', '', '');

insert into lista_valores ( LV_NOMBRE, INSTRUCCION_SQL, FILTER, ESQUEMA, DESCRIPCION)
values ('LV_CLASIFICACION_INFORMACION', 'SELECT  A.LOW_VALUE VALOR, MEANING AS DESCRIPCION
FROM   V_CG_REF_CODES A
WHERE A.NAME LIKE ''CLASIFICACION_INFORMACION''
ORDER BY 2', '', '', '');

COMMIT;
