--Insert CAMPOS_BUSQUEDA
INSERT INTO AVALUOS.CAMPOS_BUSQUEDA (CODIGO_TAREA, ID_BLOQUE, CAMPO, KEY)
VALUES ('SEGU0013', 0, 'CODIGO_USUARIO', 'HU.CODIGO_USUARIO');

INSERT INTO AVALUOS.CAMPOS_BUSQUEDA (CODIGO_TAREA, ID_BLOQUE, CAMPO, KEY)
VALUES ('SEGU0004A', 0, 'CODIGO_USUARIO', 'U.CODIGO_USUARIO');

INSERT INTO AVALUOS.CAMPOS_BUSQUEDA (CODIGO_TAREA, ID_BLOQUE, CAMPO, KEY)
VALUES ('SEGU0014', 0, 'CODIGO_PERFIL', '');

INSERT INTO AVALUOS.CAMPOS_BUSQUEDA (CODIGO_TAREA, ID_BLOQUE, CAMPO, KEY)
VALUES ('SEGU0014', 0, 'CODIGO_TAREA', 'T.CODIGO_TAREA');

COMMIT;
/
