--Insert TAREA
INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA,FECHA_TRANSACCION,USUARIO_TRANSACCION,MARCA_ACTIVO,SUB_MODULO, ORDEN,TIPO_CONTENIDO,CONTENIDO,
                           CLASIFICACION_INF, CRITICIDAD_INF,MENSAJE_MANTENIMIENTO)
VALUES ('SEGU0013','SEGURIDAD','CONSULTA - HISTORICO USUARIOS APLICATIVO', 'FO', to_date('07-09-2015', 'dd-mm-yyyy'),'TRON2000D','S',null,
        null,null,null,null,null,null);

INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION,USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO, DETALLE_FUNCIONAL)
VALUES ('SEGU0013A', 'SEGURIDAD', 'CONSULTA - HISTORICO USUARIOS APLICATIVO', 'RE',to_date('21-10-2015', 'dd-mm-yyyy'), 'TRON2000D', 'N', '', null, 
        null, '', null, null, '', '');

INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION, USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO, DETALLE_FUNCIONAL)
VALUES ('SEGU0004A', 'SEGURIDAD', 'CONSULTA - USUARIOS DEL SISTEMA', 'RE', to_date('21-10-2015', 'dd-mm-yyyy'), 'TRON2000D', 'S', 
        '', null, null, '', null, null, '', '');

INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION, USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO, DETALLE_FUNCIONAL)
VALUES ('SEGU0004B', 'SEGURIDAD', 'CONSULTA - USUARIOS DEL SISTEMA', 'RE', to_date('21-10-2015', 'dd-mm-yyyy'), 'TRON2000D', 'N', '', null, 
        null, '', null, null, '', '');

INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION, USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO)
VALUES ('SEGU0006', 'SEGURIDAD', 'CONSULTA - OPCIONES APLICATIVO', 'RE', to_date('07-09-2015', 'dd-mm-yyyy'), 'TRON2000D', 'S', '', null, 
        null, '', null, null, '');
        
INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION, USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO, DETALLE_FUNCIONAL)
VALUES ('SEGU0006A', 'SEGURIDAD', 'CONSULTA - OPCIONES APLICATIVO', 'RE', to_date('21-10-2015', 'dd-mm-yyyy'), 'TRON2000D', 'N', '', null, 
        null, '', null, null, '', '');

INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION, USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO)
VALUES ('SEGU0014', 'SEGURIDAD', 'CONSULTA - PERFILES POR OPCIÓN', 'RE', to_date('21-10-2015', 'dd-mm-yyyy'), 'TRON2000D', 'S', '', null, 
        null, '', null, null, '');

INSERT INTO AVALUOS.TAREA (CODIGO_TAREA, CODIGO_MODULO, DESCRIPCION_TAREA, TIPO_TAREA, FECHA_TRANSACCION, USUARIO_TRANSACCION, MARCA_ACTIVO, SUB_MODULO, ORDEN, TIPO_CONTENIDO, CONTENIDO, 
                           CLASIFICACION_INF, CRITICIDAD_INF, MENSAJE_MANTENIMIENTO, DETALLE_FUNCIONAL)
VALUES ('SEGU0014A', 'SEGURIDAD', 'CONSULTA - PERFILES POR OPCIÓN', 'RE', to_date('21-10-2015', 'dd-mm-yyyy'), 'TRON2000D', 'N', '', null, 
        null, '', null, null, '', '');
                              
COMMIT;
/
