--INSERT V_CG_REF_CODES

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CLASIFICACION_INFORMACION', '1', '', 'CON', 'CONFIDENCIAL', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CLASIFICACION_INFORMACION', '2', '', 'SEC', 'SECRETA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CLASIFICACION_INFORMACION', '3', '', 'INT', 'USO INTERNO', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CLASIFICACION_INFORMACION', '4', '', 'PUB', 'PUBLICA', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

INSERT INTO AVALUOS.CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING, RV_CREATE_BY, ID_CG_REF_CODES)
VALUES ('CLASIFICACION_INFORMACION', '5', '', 'P', 'PENDIENTE', 'SEGURIDAD', AVALUOS.SEQ_CG_REF_CODES.NEXTVAL);

COMMIT;
/
