update tarea_proceso 
   set instruccion = 
'SELECT CODIGO_TAREA AS TAREA,
     CODIGO_MODULO AS MODULO,
     SF_NOMBRE_MODULO(CODIGO_MODULO) NOMBRE_MODULO,
     DESCRIPCION_TAREA AS DESCRIPCION,
     TIPO_TAREA AS TIPO_TAREA,
     SF_DOMINIO(''TIPO_FORMA'',TIPO_TAREA, ''SEGURIDAD'') PRESENTACION,
     MARCA_ACTIVO AS ACTIVA,
     SF_DOMINIO(''SI_NO'',MARCA_ACTIVO, ''SEGURIDAD'') ESTA_ACTIVA,
     SUB_MODULO AS SUBMODULO,
     ORDEN,
     TIPO_CONTENIDO,
     SF_DOMINIO(''TIPO_CONTENIDO'',TIPO_CONTENIDO, ''SEGURIDAD'') DESC_TIPO_CONT,
     CONTENIDO,
     CLASIFICACION_INF,
     SF_DOMINIO(''CLASIFICACION_INFORMACION'',CLASIFICACION_INF,''SEGURIDAD'') DESC_CLASIFICACION,
     CRITICIDAD_INF,
     SF_DOMINIO(''CRITICIDAD_INFORMACION'',CRITICIDAD_INF,''SEGURIDAD'') DESC_CRITICIDAD,
     FECHA_TRANSACCION AS FECHA,
     USUARIO_TRANSACCION AS USUARIO
 FROM TAREA
ORDER BY 1'
where codigo_tarea = 'SEGU0001'
  and id_bloque = 0;
  
COMMIT;  

