insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CLASIFICACION_INFORMACION', '1', '', 'CON', 'CONFIDENCIAL', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CLASIFICACION_INFORMACION', '2', '', 'SEC', 'SECRETA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CLASIFICACION_INFORMACION', '3', '', 'INT', 'USO INTERNO', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CLASIFICACION_INFORMACION', '4', '', 'PUB', 'PUBLICA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CRITICIDAD_INFORMACION', '1', '', 'MB', 'MUY BAJA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CRITICIDAD_INFORMACION', '2', '', 'BJ', 'BAJA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CRITICIDAD_INFORMACION', '3', '', 'MD', 'MEDIA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CRITICIDAD_INFORMACION', '4', '', 'AL', 'ALTA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CRITICIDAD_INFORMACION', '5', '', 'MA', 'MUY ALTA', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CLASIFICACION_INFORMACION', '5', '', 'P', 'PENDIENTE', 'SEGURIDAD');

insert into cg_ref_codes ( ID_CG_REF_CODES, RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING,RV_CREATE_BY)
values (SEQ_CG_REF_CODES.NEXTVAL,'CRITICIDAD_INFORMACION', '6', '', 'P', 'PENDIENTE', 'SEGURIDAD');

COMMIT;
