--Insert CAMPOS_VALIDATE
INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0013', 0, 'TAB', 'onInsertDefaultSettingValue=validateFormItem();onEditSettingValues=validateFormItem()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0013', 0, 'BODY', 'onLoad=initForm()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0004A', 0, 'BODY', 'onLoad=initForm()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0004A', 0, 'TAB', 'onInsertDefaultSettingValue=validateFormItem();onEditSettingValues=validateFormItem()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0006', 0, 'TAB', 'onInsertDefaultSettingValue=validateFormItem();onEditSettingValues=validateFormItem()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0006', 0, 'BODY', 'onLoad=initForm()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0014', 0, 'BODY', 'onLoad=initForm()');

INSERT INTO AVALUOS.CAMPOS_VALIDATE (CODIGO_TAREA, ID_BLOQUE, CAMPO, VALIDATES)
VALUES ('SEGU0014', 0, 'TAB', 'onInsertDefaultSettingValue=validateFormItem();onEditSettingValues=validateFormItem();');

COMMIT;
/

