UPDATE AVALUOS.TAREA_PROCESO
   SET INSTRUCCION = 'SELECT CODIGO_PERFIL AS PERFIL,
NOMBRE_PERFIL  AS DESCRIPCION,
NUMERO_ACCESOS_PERFIL AS NUMERO_ACCESOS,
FECHA_VENCIMIENTO,
DETALLE_FUNCIONAL,
CARGO_FUNCIONARIO AS "DUEÑO",
FECHA_TRANSACCION AS FECHA,
USUARIO_TRANSACCION AS USUARIO
FROM PERFIL ORDER BY 2,1'
 WHERE CODIGO_TAREA =  'SEGU0002'
   AND ID_BLOQUE = '0';
   
COMMIT;
/
