--
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '1' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '1';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '2' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '10';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '3' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '11';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '3' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '12';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '3' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '13';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '4' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '14';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '4' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '15';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '5' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '16';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '5' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '17';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '5' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '18';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '5' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '19';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '1' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '2';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '6' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '20';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '6' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '21';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '1' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '3';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '1' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '4';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '1' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '5';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '1' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '6';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '2' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '7';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '2' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '8';
UPDATE AVALUOS.CG_REF_CODES SET RV_ABBREVIATION = '2' WHERE RV_DOMAIN = 'C_ESTRUCTURA_SF_BUA' AND RV_LOW_VALUE = '9';

/

COMMIT;
