
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 257;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 258;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 259;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 260;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 261;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 262;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 263;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 264;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 265;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 266;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 267;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 268;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 269;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 270;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 271;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 272;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 273;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 274;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 275;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 276;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 277;
DELETE FROM AVALUOS.PGB_ARCHIVO_PLANO WHERE CONSECUTIVO_PLANO = 278;


--
-- Updating data of table AVALUOS.PGB_ARCHIVO_PLANO
--
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S' WHERE CONSECUTIVO_PLANO = 10;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S' WHERE CONSECUTIVO_PLANO = 54;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFINMUEBLE', COLUMNA_BD = 'IDCATEGORIA', TIPO_DATO = 'NUMBER', FORMATO = NULL, DOMINIO = 'CATEGORIA', OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', OBLIGATORIEDAD_OFICINA = 'S', DESCRIPCION_CAMPO = 'CATEGORIA' WHERE CONSECUTIVO_PLANO = 222;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_AVALUOS', COLUMNA_BD = 'T_USUARIO', TIPO_DATO = 'VARCHAR2', FORMATO = '30', DOMINIO = NULL, OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', DESCRIPCION_CAMPO = 'Usuario Avalúo', LONGITUD_VISUAL_CAMPO = 30 WHERE CONSECUTIVO_PLANO = 223;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_AVALUOS', COLUMNA_BD = 'T_SECTOR', FORMATO = NULL, DOMINIO = 'SECTOR', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Sector' WHERE CONSECUTIVO_PLANO = 224;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_AVALUOS', COLUMNA_BD = 'A_SOLTEL', FORMATO = '10', DOMINIO = NULL, OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Teléfono fijo del solicitante', LONGITUD_VISUAL_CAMPO = 32 WHERE CONSECUTIVO_PLANO = 225;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_AVALUOS', COLUMNA_BD = 'A_SOLCEL', FORMATO = '10', DOMINIO = NULL, OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Télefono movil del solicitante', LONGITUD_VISUAL_CAMPO = 33 WHERE CONSECUTIVO_PLANO = 226;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET COLUMNA_BD = 'A_SOLCORREO', TIPO_DATO = 'VARCHAR2(30)', FORMATO = '60', DOMINIO = NULL, OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', OBLIGATORIEDAD_OFICINA = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Correo electrónico del solicitante', LONGITUD_VISUAL_CAMPO = 60 WHERE CONSECUTIVO_PLANO = 227;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_AVALUOS', COLUMNA_BD = 'A_UBICGPS', TIPO_DATO = 'VARCHAR2', FORMATO = '30', DOMINIO = NULL, OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', OBLIGATORIEDAD_OFICINA = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Coordenadas Longitudinales y Latitudinales', LONGITUD_VISUAL_CAMPO = 45 WHERE CONSECUTIVO_PLANO = 228;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFCONSTRUCCION', COLUMNA_BD = 'A_UBICFUENTESH', TIPO_DATO = 'NUMBER', FORMATO = NULL, DOMINIO = 'AFIRMAR', OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', OBLIGATORIEDAD_OFICINA = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Cercanía a rios, caños, fuentes hídricas', LONGITUD_VISUAL_CAMPO = 43 WHERE CONSECUTIVO_PLANO = 229;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET COLUMNA_BD = ' A_UBICNIVELZ ', FORMATO = NULL, DOMINIO = 'NIVEL', OBLIGATORIEDAD_LOTE = 'S', OBLIGATORIEDAD_LOTEURBANO = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Edificación vs vía ' WHERE CONSECUTIVO_PLANO = 230;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFBARRIO', COLUMNA_BD = 'A_EDIIGUALES', FORMATO = NULL, DOMINIO = NULL, ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Edificaciones similares barrio', LONGITUD_VISUAL_CAMPO = 33 WHERE CONSECUTIVO_PLANO = 231;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFCONSTRUCCION', COLUMNA_BD = ' A_LUCES ', TIPO_DATO = 'NUMBER', FORMATO = NULL, DOMINIO = 'LUCES', OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Longitud luces' WHERE CONSECUTIVO_PLANO = 232;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFINMUEBLE', COLUMNA_BD = 'A_EDICONSTUSO', FORMATO = NULL, DOMINIO = 'AFIRMAR', OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Construido para el uso actual', LONGITUD_VISUAL_CAMPO = 32 WHERE CONSECUTIVO_PLANO = 233;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFCONSTRUCCION', COLUMNA_BD = 'A_EDIPISO', DOMINIO = NULL, OBLIGATORIEDAD_LOTE = 'N', OBLIGATORIEDAD_LOTEURBANO = 'N', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Piso del Inmueble' WHERE CONSECUTIVO_PLANO = 234;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET TABLA_BD = 'PGB_INFCONSTRUCCION', COLUMNA_BD = 'A_EDISIMALT', TIPO_DATO = 'NUMBER', FORMATO = NULL, DOMINIO = 'SIMETRIA', OBLIGATORIEDAD_LOTE = 'N', OBLIGATORIEDAD_LOTEURBANO = 'N', ES_ASOBANCARIA = 'N', DESCRIPCION_CAMPO = 'Simetría en altura', LONGITUD_VISUAL_CAMPO = 24 WHERE CONSECUTIVO_PLANO = 235;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', DESCRIPCION_CAMPO = 'Simetría en planta' WHERE CONSECUTIVO_PLANO = 236;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S' WHERE CONSECUTIVO_PLANO = 237;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', DESCRIPCION_CAMPO = 'Ubicación tanques de agua' WHERE CONSECUTIVO_PLANO = 240;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', DESCRIPCION_CAMPO = 'Hay Sobrepeso' WHERE CONSECUTIVO_PLANO = 242;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', DESCRIPCION_CAMPO = 'Hay Asentamientos' WHERE CONSECUTIVO_PLANO = 244;
UPDATE AVALUOS.PGB_ARCHIVO_PLANO SET OBLIGATORIEDAD_APARTAMENTO = 'S', OBLIGATORIEDAD_BODEGA = 'S', OBLIGATORIEDAD_CASA = 'S', OBLIGATORIEDAD_CASARURAL = 'S', OBLIGATORIEDAD_LOCAL = 'S', OBLIGATORIEDAD_OFICINA = 'S', DESCRIPCION_CAMPO = 'Existen Daños previos' WHERE CONSECUTIVO_PLANO = 245;
