ALTER TABLE HISTORICO_TAREA_PERFIL ADD (
  CONSTRAINT AVCON_59022_PERMI_ACT
 CHECK (   PERMISO_ACTUALIZACION = 'S' OR PERMISO_ACTUALIZACION = 'N'),
  CONSTRAINT AVCON_59022_PERMI_ADIC
 CHECK (   PERMISO_ADICIONAR = 'N' OR PERMISO_ADICIONAR = 'S'),
  CONSTRAINT AVCON_59022_PERMI_BORR
 CHECK (   PERMISO_BORRAR = 'N' OR PERMISO_BORRAR = 'S'),
  CONSTRAINT AVCON_59022_PERMI_CONS
 CHECK (   PERMISO_CONSULTAR = 'N' OR PERMISO_CONSULTAR = 'S'),
  CONSTRAINT AVCON_59022_PERMI_EJEC
 CHECK (   PERMISO_EJECUTAR = 'S' OR PERMISO_EJECUTAR = 'N'),
  CONSTRAINT AVCON_59022_PERMI_IMP
 CHECK (   PERMISO_IMPRIMIR = 'N' OR PERMISO_IMPRIMIR = 'S'),
  CONSTRAINT HIS_TAR_PER_PK
 PRIMARY KEY
 (CODIGO_TAREA, CODIGO_PERFIL, SECUENCIA_HISTORICO));
