ALTER TABLE PGB_CARGUE_TMP DROP CONSTRAINT ESTADO_CARGUE;
ALTER TABLE PGB_CARGUE_TMP DROP CONSTRAINT TIPO_CARGUE;

ALTER TABLE PGB_CARGUE_TMP ADD (
  CONSTRAINT CK_PGB_CARGUE_ESTADO_CARGUE_01
 CHECK (ESTADO_CARGUE = 'CARGADO' OR (ESTADO_CARGUE = 'APLICADO' OR ESTADO_CARGUE = 'RECHAZADO')),
  CONSTRAINT CK_PGB_CARGUE_TIPO_CARGUE_01
 CHECK (TIPO_CARGUE = 'CARGUE' OR TIPO_CARGUE = 'DESCARGA' OR TIPO_CARGUE = 'VALIDAWEB'));