ALTER TABLE T_MODULOS_PERFIL ADD (
  CONSTRAINT T_USUARIO_MOD_PERF_FK 
 FOREIGN KEY (PERFIL) 
 REFERENCES T_USUARIO (CODIGO_PERFIL),
  CONSTRAINT T_MOD_PER_MOD_PER_FK 
 FOREIGN KEY (MODULO_PADRE, PERFIL_PADRE) 
 REFERENCES T_MODULOS_PERFIL (MODULO,PERFIL));
