ALTER TABLE TAREA_PERFIL ADD (
  CONSTRAINT AVCON_59022_PERMI_000
 CHECK (   PERMISO_EJECUTAR = 'S' OR PERMISO_EJECUTAR = 'N'),
  CONSTRAINT AVCON_59022_PERMI_001
 CHECK (   PERMISO_IMPRIMIR = 'N' OR PERMISO_IMPRIMIR = 'S'),
  CONSTRAINT AVCON_59022_PERMI_002
 CHECK (   PERMISO_ACTUALIZACION = 'S' OR PERMISO_ACTUALIZACION = 'N'),
  CONSTRAINT AVCON_59022_PERMI_003
 CHECK (   PERMISO_ADICIONAR = 'N' OR PERMISO_ADICIONAR = 'S'),
  CONSTRAINT AVCON_59022_PERMI_004
 CHECK (   PERMISO_BORRAR = 'N' OR PERMISO_BORRAR = 'S'),
  CONSTRAINT AVCON_59022_PERMI_005
 CHECK (   PERMISO_CONSULTAR = 'N' OR PERMISO_CONSULTAR = 'S'),
  CONSTRAINT TAR_PER_PK
 PRIMARY KEY
 (CODIGO_TAREA, CODIGO_PERFIL));
