CREATE OR REPLACE VIEW V_USUARIO
AS 
SELECT CODIGO_USUARIO,
       CODIGO_PERFIL,
       CODIGO_LOCALIDAD,
       CONTADOR_ACCESOS,
       FECHA_ACTIVACION,
       INDICADOR_NIVEL_SUPERVISION,
       ESTADO_USUARIO,
       CEDULA_EMPLEADO,
       CODIGO_EMPLEADO,
       NOMBRE_EMPLEADO,
       TELEFONO_EMPLEADO,
       COD_CIA
  FROM USUARIO;


