-- Add/modify TAREA columns 
ALTER TABLE AVALUOS.TAREA ADD MENSAJE_MANTENIMIENTO VARCHAR2(2000);
COMMENT ON COLUMN AVALUOS.TAREA.MENSAJE_MANTENIMIENTO IS 'Mensaje de Mantenimiento';

ALTER TABLE AVALUOS.TAREA ADD DETALLE_FUNCIONAL VARCHAR2(1000);
COMMENT ON COLUMN AVALUOS.TAREA.DETALLE_FUNCIONAL IS 'Descripción de la funcionalidad de la tarea';
/
