-- Add/modify PERFIL columns 
ALTER TABLE AVALUOS.PERFIL ADD DETALLE_FUNCIONAL VARCHAR2(1000);
COMMENT ON COLUMN AVALUOS.PERFIL.DETALLE_FUNCIONAL IS 'Descripción de la funcionalidad del perfil';

ALTER TABLE AVALUOS.PERFIL ADD CARGO_FUNCIONARIO VARCHAR2(500);
COMMENT ON COLUMN AVALUOS.PERFIL.CARGO_FUNCIONARIO IS 'Cargo del funcionario autorizado';

/
