ALTER TRIGGER AVALUOS.TR_AI_AU_INFCONSTRUCCION DISABLE;
ALTER TRIGGER AVALUOS.TR_AI_AU_INFINMUEBLE DISABLE;
ALTER TRIGGER AVALUOS.TR_AID_AVALUO DISABLE;
ALTER TRIGGER AVALUOS.TR_AU_ESTADO_AVALUO DISABLE;
ALTER TRIGGER AVALUOS.TR_BIU_PGB_AVALUOS DISABLE;
/