CREATE OR REPLACE FUNCTION Sf_Describ_Tarea(IN_COD_TAREA  IN VARCHAR2) RETURN VARCHAR2 IS
W_DESC_TAREA    VARCHAR2(80);
BEGIN
  BEGIN
     SELECT  NVL(DESCRIPCION_TAREA,'')
      INTO    W_DESC_TAREA
      FROM    TAREA
      WHERE   CODIGO_TAREA= IN_COD_TAREA;
	EXCEPTION WHEN OTHERS THEN
             W_DESC_TAREA := '';
   END;
RETURN W_DESC_TAREA;
END Sf_Describ_Tarea;
/


