CREATE OR REPLACE FUNCTION Sf_Dominio(P_LV  IN VARCHAR2, P_VALUE IN VARCHAR2, P_USER VARCHAR2) RETURN VARCHAR2 IS
W_DESC_TAREA    VARCHAR2(80);
BEGIN
  BEGIN
    SELECT MEANING INTO W_DESC_TAREA
    FROM  V_CG_REF_CODES A
    WHERE A.NAME = P_LV
--    AND	A.CREATED_BY = P_USER
	AND A.LOW_VALUE  = P_VALUE;

	EXCEPTION
      WHEN NO_DATA_FOUND THEN
        W_DESC_TAREA := '';
	  WHEN OTHERS THEN
        W_DESC_TAREA := SUBSTR(SQLERRM,1,80);
   END;
RETURN W_DESC_TAREA;
END ;
/
