CREATE OR REPLACE FUNCTION Sf_Describ_Perfil(IN_COD_PERFIL  IN VARCHAR2) RETURN VARCHAR2 IS
W_DESC_PERFIL    VARCHAR2(80);
BEGIN
  BEGIN
     SELECT  NVL(NOMBRE_PERFIL,'')
      INTO    W_DESC_PERFIL
      FROM    PERFIL
      WHERE   CODIGO_PERFIL= IN_COD_PERFIL;
	EXCEPTION WHEN OTHERS THEN
             W_DESC_PERFIL := '';
   END;
RETURN W_DESC_PERFIL;
END Sf_Describ_Perfil;
/


