CREATE OR REPLACE FUNCTION Sf_Localidad(P_AGENCIA  IN VARCHAR2) RETURN VARCHAR2 IS
W_DESC_TAREA    VARCHAR2(80);
BEGIN
  BEGIN
    SELECT NOM_AGENCIA NOMBRE INTO W_DESC_TAREA
    FROM A1000702
    WHERE COD_AGENCIA = p_AGENCIA;
	EXCEPTION
      WHEN NO_DATA_FOUND THEN
        W_DESC_TAREA := '';
	  WHEN OTHERS THEN
        W_DESC_TAREA := SUBSTR(SQLERRM,1,80);
   END;
RETURN W_DESC_TAREA;
END ;
/


