CREATE OR REPLACE FUNCTION AVALUOS.Sf_NOMBRE_EMPLEADO(IN_CODIGO_USUARIO IN VARCHAR2)
   RETURN VARCHAR2 IS
--
NOMBRE_USUARIO VARCHAR2(60);
--
BEGIN
   --
	 BEGIN
      --
    	SELECT NOMBRE_EMPLEADO 
        INTO NOMBRE_USUARIO
        FROM USUARIO U 
       WHERE U.CODIGO_USUARIO = IN_CODIGO_USUARIO; 
      --
      EXCEPTION WHEN NO_DATA_FOUND THEN
         --
         NOMBRE_USUARIO := NULL;
         --
      END;
      --
   RETURN(NOMBRE_USUARIO);
   --
END ;
/
