CREATE OR REPLACE FUNCTION Sf_Nombre_Modulo(IN_CODIGO_MODULO IN VARCHAR2
                                              )RETURN VARCHAR2 IS
MODULO_ALTERNO VARCHAR2(250);
BEGIN
 BEGIN
     SELECT  DESCRIPCION_MODULO
        INTO MODULO_ALTERNO
        FROM MODULO_APLICACION
        WHERE CODIGO_MODULO=IN_CODIGO_MODULO;
        EXCEPTION WHEN NO_DATA_FOUND THEN
         MODULO_ALTERNO:=NULL;
    END;
  RETURN(MODULO_ALTERNO);
END ;
/


